import assert from 'node:assert/strict';
import {createAlerts,ALERT_POLICY} from '../dist/alerts.js';
import {GRID} from '../dist/geometry.js';

let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function fixture(policy={}){let now=0;const alerts=createAlerts({clock:()=>now,policy});return{alerts,time:t=>{now=t;},source:{id:9,team:1},unit:{id:1,team:0,x:100,y:200,hp:45},building:{id:2,team:0,x:120,y:220,building:true,hp:1500}};}

test('Location-bearing transmissions are snapshotted for recall',()=>{const f=fixture(),p={x:10,y:20};f.alerts.transmit('Marine ready',p);p.x=1000;assert.equal(f.alerts.recall().x,10);});
test('Pointless notices cannot become camera recall targets',()=>{const f=fixture();assert.equal(f.alerts.transmit('No unit selected',null),null);assert.equal(f.alerts.recall(),null);});
test('Non-finite target coordinates cannot enter history',()=>{const f=fixture();assert.equal(f.alerts.transmit('bad',{x:NaN,y:4}),null);assert.equal(f.alerts.transmit('bad',{x:4,y:Infinity}),null);assert.equal(f.alerts.history().length,0);});
test('Zero coordinates are valid locations',()=>{const f=fixture();f.alerts.transmit('Origin',{x:0,y:0});assert.equal(f.alerts.recall().x,0);});
test('Errors are display-only and excluded from Space history',()=>{const f=fixture();assert.equal(f.alerts.error('Not enough minerals').kind,'error');assert.equal(f.alerts.history().length,0);assert.equal(f.alerts.transmit('Error',{x:10,y:20},{kind:'error'}),null);});
test('Empty messages are rejected rather than creating invisible rows',()=>{const f=fixture();assert.equal(f.alerts.transmit(' ',f.unit),null);assert.equal(f.alerts.error(' '),null);});
test('Recall cycles the most recent eight location-bearing transmissions',()=>{const f=fixture();for(let i=0;i<12;i++)f.alerts.transmit('Ready '+i,{x:i,y:0});const ids=Array.from({length:9},()=>f.alerts.recall().x);assert.deepEqual(ids,[11,10,9,8,7,6,5,4,11]);});
test('An error does not interrupt the existing recall cycle',()=>{const f=fixture();f.alerts.transmit('Older',{x:1,y:1});f.alerts.transmit('Newer',{x:2,y:2});assert.equal(f.alerts.recall().x,2);f.alerts.error('Cannot place');assert.equal(f.alerts.recall().x,1);});
test('A fresh transmission starts recall from the newest event',()=>{const f=fixture();f.alerts.transmit('Older',{x:1,y:1});f.alerts.recall();f.alerts.transmit('Newer',{x:2,y:2});assert.equal(f.alerts.recall().x,2);});
test('Transmission history is bounded without disturbing recent ordering',()=>{const f=fixture();for(let i=0;i<100;i++)f.alerts.transmit('Ready '+i,{x:i,y:0});assert.equal(f.alerts.history().length,ALERT_POLICY.historyLimit);assert.equal(f.alerts.history()[0].x,99);assert.equal(f.alerts.history().at(-1).x,20);});
test('Hostile damage creates a forces warning and minimap pulse',()=>{const f=fixture();const warning=f.alerts.onDamage(f.source,f.unit,6);assert.equal(warning.kind,'attackUnit');assert.equal(warning.text,'Our forces are under attack!');assert.deepEqual({x:warning.x,y:warning.y},{x:100,y:200});assert.equal(f.alerts.pings().length,1);});
test('A building hit creates the distinct base warning',()=>{const f=fixture();assert.equal(f.alerts.onDamage(f.source,f.building,6).kind,'attackTown');});
test('Fatal hits still alert even if the victim is already dead',()=>{const f=fixture();f.unit.hp=-5;assert.equal(f.alerts.onDamage(f.source,f.unit,50).kind,'attackUnit');});
test('An already-dead missile source still identifies hostile impact',()=>{const f=fixture();f.source.hp=0;assert.equal(f.alerts.onDamage(f.source,f.unit,6).kind,'attackUnit');});
test('Friendly fire cannot generate an enemy attack warning',()=>{const f=fixture();assert.equal(f.alerts.onDamage({id:8,team:0},f.unit,6),null);assert.equal(f.alerts.history().length,0);});
test('Damage dealt to an enemy creates no own-team warning',()=>{const f=fixture();assert.equal(f.alerts.onDamage({team:0},{...f.unit,team:1},6),null);});
test('No damage and invalid damage do not create warnings',()=>{const f=fixture();for(const amount of [0,-1,NaN,Infinity])assert.equal(f.alerts.onDamage(f.source,f.unit,amount),null);assert.equal(f.alerts.history().length,0);});
test('Missing source or non-finite source team cannot create warnings',()=>{const f=fixture();assert.equal(f.alerts.onDamage(null,f.unit,6),null);assert.equal(f.alerts.onDamage({},f.unit,6),null);});
test('Nearby rapid damage is combined instead of flooding history',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);for(let i=1;i<=30;i++){f.time(i/10);assert.equal(f.alerts.onDamage(f.source,{...f.unit,x:150},6),null);}assert.equal(f.alerts.history().length,1);assert.equal(f.alerts.history()[0].hits,31);});
test('The native-catalog radius boundary is inclusive in this policy',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);assert.equal(f.alerts.onDamage(f.source,{...f.unit,x:f.unit.x+15*GRID},6),null);});
test('Separate distant battles can emit two independent warnings',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);const remote=f.alerts.onDamage(f.source,{...f.unit,x:900},6);assert.ok(remote);assert.equal(f.alerts.history().length,2);});
test('A third active distant battle is rate-limited by the shared global policy',()=>{const f=fixture();for(const x of [100,900])f.alerts.onDamage(f.source,{...f.unit,x},6);assert.equal(f.alerts.onDamage(f.source,{...f.unit,x:1700},6),null);assert.equal(f.alerts.history().length,2);});
test('Sustained attacks can warn again after the overlap window expires',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);f.time(14.99);assert.equal(f.alerts.onDamage(f.source,f.unit,6),null);f.time(15);assert.ok(f.alerts.onDamage(f.source,f.unit,6));assert.equal(f.alerts.history().length,2);});
test('Nearby building damage supersedes a forces warning without another history row',()=>{const f=fixture();const unitWarning=f.alerts.onDamage(f.source,f.unit,6);f.time(1);const baseWarning=f.alerts.onDamage(f.source,f.building,6);assert.equal(baseWarning.id,unitWarning.id);assert.equal(baseWarning.kind,'attackTown');assert.equal(f.alerts.history().length,1);assert.equal(f.alerts.recall().unitId,f.building.id);});
test('A unit hit cannot downgrade a base warning',()=>{const f=fixture();f.alerts.onDamage(f.source,f.building,6);f.time(1);assert.equal(f.alerts.onDamage(f.source,f.unit,6),null);assert.equal(f.alerts.history()[0].kind,'attackTown');});
test('Later victim motion cannot drag historical camera targets',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);f.unit.x=1000;f.source.x=1500;assert.equal(f.alerts.recall().x,100);assert.equal(f.alerts.pings()[0].x,100);});
test('Expired pings stop flashing while history remains available for recall',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);f.time(6);assert.equal(f.alerts.pings().length,0);assert.equal(f.alerts.recall().kind,'attackUnit');});
test('Mutating a returned warning cannot alter internal history',()=>{const f=fixture();const warning=f.alerts.onDamage(f.source,f.unit,6);warning.x=999;f.alerts.history()[0].x=888;f.alerts.pings()[0].x=777;assert.equal(f.alerts.recall().x,100);});
test('Other notifications do not consume attack overlap capacity',()=>{const f=fixture();for(let i=0;i<10;i++)f.alerts.transmit('Complete',{x:i,y:20});assert.ok(f.alerts.onDamage(f.source,f.unit,6));});
test('History eviction cannot reset active attack suppression',()=>{const f=fixture({historyLimit:3});f.alerts.onDamage(f.source,f.unit,6);for(let i=0;i<4;i++)f.alerts.transmit('Complete',{x:i,y:20});assert.equal(f.alerts.onDamage(f.source,f.unit,6),null);assert.equal(f.alerts.pings().length,1);});
test('Evicted active forces warning can be recalled after a base upgrade',()=>{const f=fixture({historyLimit:3});f.alerts.onDamage(f.source,f.unit,6);for(let i=0;i<4;i++)f.alerts.transmit('Complete',{x:i,y:20});f.time(1);assert.equal(f.alerts.onDamage(f.source,f.building,6).kind,'attackTown');assert.equal(f.alerts.recall().kind,'attackTown');assert.equal(f.alerts.history().length,3);});
test('Policy overrides remain explicit for integration testing',()=>{const f=fixture({attackWindow:2,pingDuration:1,historyLimit:3,recallLimit:2});f.alerts.onDamage(f.source,f.unit,6);f.time(1);assert.equal(f.alerts.pings().length,0);f.time(2);assert.ok(f.alerts.onDamage(f.source,f.unit,6));for(let i=0;i<5;i++)f.alerts.transmit('Ready',{x:i,y:0});assert.equal(f.alerts.history().length,3);assert.deepEqual([f.alerts.recall().x,f.alerts.recall().x,f.alerts.recall().x],[4,3,4]);});
test('Reset clears historical warnings, overlap limits, pings and recall position',()=>{const f=fixture();f.alerts.onDamage(f.source,f.unit,6);f.alerts.reset();assert.equal(f.alerts.recall(),null);assert.equal(f.alerts.pings().length,0);assert.equal(f.alerts.history().length,0);assert.equal(f.alerts.onDamage(f.source,f.unit,6).id,1);});
console.log(`${passed} alert checks passed`);
