"""Live renderer state/action integration, beyond pure authored pose tests."""
import shutil,json
from pathlib import Path
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);page=b.new_page(viewport={'width':1440,'height':900});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game');page.click('#launch');page.evaluate('__game.running=false;__game.aiEnabled=false')
 def check(name,ok,detail=None):print(('PASS' if ok else 'FAIL'),name,json.dumps(detail));assert ok,name
 def setup(script):page.evaluate(script);page.wait_for_timeout(120)
 setup('''()=>{const g=__game;for(const w of g.entities.filter(e=>e.type==='worker'))g.stop(w);const n=g.minerals[3],w=g.entities.find(e=>e.type==='worker');w.x=n.x+50;w.y=n.y;g.issue(w,{kind:'mine',node:n});for(let i=0;i<600&&w.order.phase!=='harvest';i++)g.update(1/60);if(w.order.phase!=='harvest')throw Error('Worker never reached harvest');w.mineTime=0;const r=w.harvestResource;w.angle=Math.atan2(r.y-w.y,r.x-w.x)+Math.PI;w.testTarget=r;g.testWorker=w.id;for(let i=0;i<12;i++)g.update(1/60)}''')
 r=page.evaluate('''()=>{const g=__game,w=g.entities.find(e=>e.id===g.testWorker),a=Math.atan2(w.testTarget.y-w.y,w.testTarget.x-w.x);return{phase:w.order.phase,error:Math.abs(Math.atan2(Math.sin(a-w.angle),Math.cos(a-w.angle))),mesh:g.view.objects.get(w.id).userData.unitAnimation.tool!==null}}''');check('Harvesting worker keeps turning toward its work target',r['phase']=='harvest' and r['error']<.02 and r['mesh'],r)
 setup('''()=>{const g=__game;g.reset();g.start();g.running=false;g.aiEnabled=false;g.camera.x=750;g.camera.y=1000;const w=g.spawn('worker',0,680,1000),c=g.spawn('relay',0,750,1000,false);c.builder=w;g.issue(w,{kind:'build',target:c});for(let i=0;i<100;i++)g.update(1/60);w.angle=Math.PI;for(let i=0;i<12;i++)g.update(1/60);g.testWorker=w.id;g.selected=[w]}''');check('Construction work turns the SCV to its structure',page.evaluate('''()=>{const g=__game,w=g.selected[0],b=w.order.target,a=Math.atan2(b.y-w.y,b.x-w.x);return Math.abs(Math.atan2(Math.sin(a-w.angle),Math.cos(a-w.angle)))<.02}'''))
 # A reset must bind picking and animation to the new entity even when IDs match.
 old=page.evaluate('__game.view.objects.get(1).uuid');setup('__game.reset();__game.start();__game.running=false;__game.aiEnabled=false');r=page.evaluate('''()=>{const g=__game,e=g.entities.find(e=>e.id===1),m=g.view.objects.get(1);return{uuid:m.uuid,current:m.userData.entity===e,lift:m.userData.buildingAnimation.lift}}''');check('Scenario reset replaces stale actor identity without retaining pose',r['uuid']!=old and r['current'] and r['lift']==0,r)
 r=page.evaluate('''()=>{const g=__game,c=g.entities.find(e=>e.type==='core'&&!e.team);return g.view.workerStatuses.get(c.id)}''');check('Command Center mineral label starts with twelve of sixteen',r['count']==12 and r['ideal']==16,r)
 setup('''()=>{const g=__game;const c=g.entities.find(e=>e.type==='core'&&!e.team),gas=g.geysers[1],ref=g.spawn('refinery',0,gas.x,gas.y);ref.geyser=gas;g.testRef=ref.id;g.entities.filter(e=>e.type==='worker'&&!e.team).slice(0,3).forEach(w=>g.issue(w,{kind:'gas',target:ref}));g.selected=[c,ref]}''');r=page.evaluate('''()=>{const g=__game,c=g.entities.find(e=>e.type==='core'&&!e.team),r=g.entities.find(e=>e.id===g.testRef);return{mineral:g.view.workerStatuses.get(c.id),gas:g.view.workerStatuses.get(r.id)}}''');check('Mineral and gas labels distinguish worker assignments',r['mineral']['count']==9 and r['gas']['count']==3 and r['gas']['ideal']==3,r)
 setup('''()=>{const g=__game;g.selected=[g.entities.find(e=>e.type==='core'&&!e.team)];g.selected[0].flying=true;g.invalidateNav()}''');check('Flying base hides mineral saturation status',page.evaluate('!__game.view.workerStatuses.has(__game.selected[0].id)'))
 setup('''()=>{const g=__game,n=g.minerals[3];n.amount=n.capacity*.90;g.testMineral=n;g.camera.x=n.x+150;g.camera.y=n.y;g.view.setCamera(g.camera)}''');r=page.evaluate('({state:__game.testMineral.mesh.userData.visualState,scale:__game.testMineral.mesh.scale.x})');check('Fuller minerals select a discrete actor group at fixed scale',r['state']==3 and r['scale']==1,r)
 setup('__game.testMineral.amount=__game.testMineral.capacity*.60');r=page.evaluate('({state:__game.testMineral.mesh.userData.visualState,visible:__game.testMineral.mesh.userData.resourceLevels.map(m=>m.visible),scale:__game.testMineral.mesh.scale.x})');check('Mineral depletion changes geometry group without shrinking footprint',r['state']==2 and r['visible']==[False,False,True,False] and r['scale']==1,r)
 setup('''()=>{const g=__game;g.camera.x=850;g.camera.y=1000;g.view.setCamera(g.camera);const m=g.spawn('marine',0,850,970);g.stop(m,true);m.pangle=-1;m.angle=1;g.testMarine=m.id;g.selected=[m]}''');check('Rendered heading reaches simulation heading without extra exponential lag',page.evaluate('Math.abs(__game.view.objects.get(__game.testMarine).rotation.y+1)<1e-9'))
 setup('''()=>{const g=__game;const e=g.selected[0],t=g.spawn('marine',1,e.x+110,e.y);g.stop(t,true);g.issue(e,{kind:'attack',target:t});g.update(0);for(let i=0;i<60;i++)g.update(1/60)}''');check('Actual weapon fire drives animation telemetry',page.evaluate('''()=>{const e=__game.selected[0];return e.visualShotSerial>=1&&Number.isFinite(e.visualShotAt)}'''))
 Path('artifacts').mkdir(exist_ok=True);page.screenshot(path='artifacts/animation-fidelity-integrated.png');check('Animation integration has no page errors',not errors,errors);b.close()
