"""Live Move/AttackMove goals from measured compact native formations."""
import json,shutil
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);page=b.new_page(viewport={'width':800,'height':600});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game')
 results=page.evaluate('''()=>{const g=__game,dt=1/22.4,out=[],check=(name,pass,detail)=>out.push({name,pass:!!pass,detail}),tick=n=>{for(let i=0;i<n;i++)g.update(dt)};
 const reset=()=>{g.reset();g.start();g.running=false;g.aiEnabled=false;g.entities.splice(0);g.minerals.splice(0);g.selected=[];g.invalidateNav()};
 const pack=()=>{reset();const units=[];for(let i=0;i<24;i++)units.push(g.spawn('marine',0,700+i%6*28,1100+Math.floor(i/6)*28));g.selected=units;return units};
 const command=kind=>{g.running=true;g.command(1200,1200,false,false,kind);g.running=false};
 let units=pack(),initial=units.map(u=>({x:u.x,y:u.y}));command('move');const goals=units.map(u=>({x:u.order.x,y:u.order.y}));check('Compact Move keeps 24 distinct mean-centered destinations',units.every((u,i)=>u.order.formation==='preserved'&&Math.abs(u.order.x-(1130+i%6*28))<1e-8&&Math.abs(u.order.y-(1158+Math.floor(i/6)*28))<1e-8));check('Per-unit destinations retain the shared clicked goal as metadata',units.every(u=>u.order.groupGoal.x===1200&&u.order.groupGoal.y===1200));check('Accepting compact Move leaves every unit at its current position',units.every((u,i)=>u.x===initial[i].x&&u.y===initial[i].y));tick(1);const delta={x:units[0].x-initial[0].x,y:units[0].y-initial[0].y};check('The first movement loop preserves rigid parallel offsets without update-order drift',units.every((u,i)=>Math.abs(u.x-initial[i].x-delta.x)<1e-8&&Math.abs(u.y-initial[i].y-delta.y)<1e-8),delta);tick(180);check('Compact formation completes and retains its assigned shape',units.every((u,i)=>!u.order&&Math.hypot(u.x-goals[i].x,u.y-goals[i].y)<4.01));
 units=pack();command('attack');const march=new Map(units.map(u=>[u.id,{x:u.order.x,y:u.order.y}]));check('Compact Attack Move starts with translated per-unit march goals',units.every((u,i)=>u.order.kind==='attackMove'&&u.order.formation==='preserved'&&Math.abs(u.order.x-(1130+i%6*28))<1e-8));const t=g.spawn('tank',1,950,1160);g.stop(t,true);t.damage=0;t.hp=t.maxhp=5000;tick(80);check('Combat preserves each assigned Attack Move goal and the shared click',t.hp<5000&&units.every(u=>u.order?.kind==='attackMove'&&u.order.x===march.get(u.id).x&&u.order.y===march.get(u.id).y&&u.order.groupGoal.x===1200),{hp:t.hp});
 for(const [span,preserved] of [[5.25,true],[5.26,false]]){reset();const a=g.spawn('marine',0,700,1100),b=g.spawn('marine',0,700+span*28,1100);g.selected=[a,b];command('move');check('Marine footprint extent '+(span+.75)+' game units '+(preserved?'preserves offsets':'uses crowded arrival policy'),[a,b].every(u=>(u.order.formation==='preserved')===preserved));}
 return out;}''')
 for r in results:print(('PASS' if r['pass'] else 'FAIL'),r['name'],json.dumps(r.get('detail')),flush=True)
 assert all(r['pass'] for r in results),results;assert not errors,errors;print(str(len(results))+' formation integration checks passed; no browser exceptions.');b.close()
