"""Gameplay phase consistency, defeat, paid opponent economy and fog-safe AI."""
import json,shutil
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);page=b.new_page(viewport={'width':1440,'height':900});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game')
 results=page.evaluate('''()=>{
 const g=__game,dt=1/22.4,out=[],check=(name,pass,detail=null)=>out.push({name,pass:!!pass,detail});
 const reset=()=>{g.reset();g.start();g.running=false;g.aiEnabled=false;for(const w of g.entities.filter(e=>e.type==='worker'))g.stop(w,true)};
 reset();const issued=g.spawn('marine',0,850,900);g.issue(issued,{kind:'move',x:1000,y:900});const accepted=issued.order.acceptedLoop;check('Orders acknowledge immediately without an artificial input wait',accepted===g.simulationLoop&&issued.order.startedLoop===undefined);g.update(dt);check('Gameplay processes the acknowledged order on the following integer loop',issued.order.startedLoop===accepted+1&&g.readState().loop===accepted+1);
 for(const kind of ['move','attackMove']){reset();const unit=g.spawn('marine',0,700,690);g.issue(unit,{kind:'move',x:740,y:690});g.issue(unit,{kind,x:870,y:690},true);g.issue(unit,{kind:'move',x:680,y:700},true);const projected={x:unit.orders[0].x,y:unit.orders[0].y};for(let i=0;i<600;i++)g.update(dt);check('Queued '+kind+' into blocked terrain projects and completes its successor',g.nav.open(projected,unit.r)&&!unit.order&&!unit.orders.length&&Math.hypot(unit.x-680,unit.y-700)<unit.r+4,{projected,x:unit.x,y:unit.y,order:unit.order});}
 reset();const b=g.spawn('barracks',0,850,900),target=g.spawn('marine',1,950,1000);target.damage=0;g.stop(target,true);b.rally={kind:'move',x:1150,y:1000};b.queue=[{type:'marine',started:true,time:dt/2,total:1}];g.update(dt);const m=g.entities.find(e=>e.type==='marine'&&!e.team);check('Newly trained unit receives its rally without consuming a partial birth loop',m&&m.x===m.px&&m.y===m.py&&m.vx===0&&m.order?.kind==='move');const x=m.x;g.update(dt);check('Produced unit begins following its rally on the next loop',m.x!==x||m.y!==m.py);
 reset();const depot=g.spawn('relay',0,750,1000,false),w=g.spawn('worker',0,700,1000);depot.progress=.99;depot.hp=depot.maxhp*(.1+.9*.99)-100;depot.builder=w;g.issue(w,{kind:'build',target:depot});for(let i=0;i<50&&!depot.ready;i++)g.update(dt);check('Maintained construction preserves incoming damage on completion',depot.ready&&Math.abs(depot.hp-(depot.maxhp-100))<1e-6,{hp:depot.hp});
 reset();const addon=g.spawn('techlab',0,850,900,false);addon.autoBuild=true;addon.progress=.99;addon.hp=addon.maxhp*(.1+.9*.99)-40;for(let i=0;i<50&&!addon.ready;i++)g.update(dt);check('Automatic add-on construction preserves incoming damage',addon.ready&&Math.abs(addon.hp-(addon.maxhp-40))<1e-6,{hp:addon.hp});
 reset();const base=g.entities.find(e=>e.type==='core'&&!e.team),remaining=g.spawn('relay',0,750,1000);base.hp=0;g.update(dt);check('Losing the last Command Center does not defeat a player with another structure',!g.readState().ended);remaining.flying=true;g.update(dt);check('A surviving airborne structure still prevents defeat',!g.readState().ended);remaining.hp=0;g.update(dt);check('Destroying every actual structure ends the match',g.readState().ended&&document.querySelector('#resultTitle').textContent==='Defeat');const time=g.time;g.update(dt);check('Ended matches do not consume additional simulation loops',g.time===time);
 reset();const mover=g.spawn('marine',0,1000,650);g.issue(mover,{kind:'move',x:1200,y:650});g.update(0);let revealed=null;for(let tick=0;tick<80&&!revealed;tick++){const old={x:mover.x,y:mover.y};g.update(dt);for(let iy=1;iy<33;iy++)for(let ix=20;ix<49;ix++){const x=ix*42+21,y=iy*42+21;if(Math.hypot(x-mover.x,y-mover.y)<=mover.vision&&Math.hypot(x-old.x,y-old.y)>mover.vision){revealed={x,y,visible:g.isVisible(x,y)};break}}}check('Movement reveals newly reached vision cells within the same finished loop',revealed?.visible,revealed);
 reset();const enemyCore=g.entities.find(e=>e.type==='core'&&e.team),initial=g.entities.filter(e=>e.team===1&&e.building).length;g.aiEnabled=true;g.update(dt);check('Opponent starts from the same paid 50-mineral opening',g.entities.filter(e=>e.team===1&&e.building).length===initial);g.opponent.update();check('Unscouted player structures are absent from opponent memory',!g.opponent.state().knownEnemies.some(m=>m.building&&m.x<800));for(let i=0;i<Math.ceil(150/dt);i++)g.update(dt);const own=g.entities.filter(e=>e.team===1&&e.hp>0),buildings=own.filter(e=>e.building);check('Opponent builds a paid economy and army without free resource injection',own.some(e=>e.type==='barracks')&&own.some(e=>e.type==='marine'),{types:own.map(e=>e.type)});check('Opponent never exceeds current completed supply',g.used(1)<=g.capacity(1),{used:g.used(1),cap:g.capacity(1)});check('Opponent buildings are snapped and do not overlap each other',buildings.every((a,i)=>buildings.every((b,j)=>i===j||Math.abs(a.x-b.x)>=(a.placeWidth+b.placeWidth)*14-1e-6||Math.abs(a.y-b.y)>=(a.placeHeight+b.placeHeight)*14-1e-6)));check('Opponent local SCVs do not cross-map to player mineral fields',own.filter(e=>e.type==='worker'&&e.order?.kind==='mine').every(e=>Math.hypot(e.order.node.x-enemyCore.x,e.order.node.y-enemyCore.y)<12*28));const hiddenCore=g.entities.find(e=>e.type==='core'&&!e.team);hiddenCore.x=100;hiddenCore.y=100;g.invalidateNav();g.update(0);g.opponent.update();check('Moving a known building into fog does not expose its new live coordinates',!g.opponent.state().knownEnemies.some(m=>m.id===hiddenCore.id&&m.x===100&&m.y===100),g.opponent.state());
 return out;
 }''')
 for r in results:print(('PASS' if r['pass'] else 'FAIL'),r['name'],json.dumps(r['detail']))
 assert all(r['pass'] for r in results),[r for r in results if not r['pass']];assert not errors,errors;b.close()
