"""Real worker executor: observed cargo, exclusive slot, wait and command boundaries."""
import json,shutil
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);page=b.new_page(viewport={'width':800,'height':600});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game')
 results=page.evaluate('''async()=>{const g=__game,dt=1/22.4,out=[],check=(name,pass,detail)=>out.push({name,pass:!!pass,detail});
 const tick=n=>{for(let i=0;i<n;i++)g.update(dt)};
 const fixture=(remaining=1800)=>{g.reset();g.start();g.running=false;g.aiEnabled=false;g.entities.splice(0);g.minerals.splice(0);g.selected=[];g.spawn('core',0,630,1100);const n={x:920,y:1100,r:21,placeWidth:2,placeHeight:1,footprint:[[-28,-14],[-28,14],[28,14],[28,-14]],amount:remaining,capacity:1800};g.minerals.push(n);g.invalidateNav();const w=g.spawn('worker',0,820,1100);g.issue(w,{kind:'mine',node:n});let steps=0;while(w.order?.phase!=='harvest'&&steps++<100)tick(1);if(w.order?.phase!=='harvest')throw Error('Worker did not reach fixture');return{w,n}};
 let {w,n}=fixture();tick(44);check('No cargo or resource depletion before the 45-loop extraction boundary',w.carry===0&&n.amount===1800);tick(1);check('Extraction grants cargo and releases the exclusive field before return wait',w.carry===5&&n.amount===1795&&!w.harvestResource&&!n.harvester&&w.order.phase==='waitReturn');const at={x:w.x,y:w.y};tick(7);check('Loaded worker remains stationary through seven following wait loops',w.x===at.x&&w.y===at.y&&w.order.phase==='waitReturn'&&w.carry===5);tick(1);check('Ordinary return starts on the eighth following loop',w.order.phase==='home'&&w.x<at.x&&w.carry===5);
 for(const requestAt of [0,4]){({w,n}=fixture());tick(45+requestAt);const x=w.x,y=w.y,wallet=g.money;g.issue(w,{kind:'move',x:1100,y:1100});check('Move requested '+requestAt+' loops into return wait is accepted behind that phase',w.order.phase==='waitReturn'&&w.orders[0]?.kind==='move'&&w.orders[0].acceptedLoop===g.simulationLoop);tick(7-requestAt);check('Deferred Move retains cargo and waits until departure',w.x===x&&w.y===y&&w.order.phase==='waitReturn');tick(1);check('Deferred Move starts on the departure loop without forcing a deposit',w.order.kind==='move'&&w.x>x&&w.carry===5&&g.money===wallet&&w.order.startedLoop===g.simulationLoop);}
 ({w,n}=fixture());g.issue(w,{kind:'move',x:1100,y:1100},true);const wallet=g.money;tick(52);const x=w.x;tick(1);check('Gather plus Shift Move leaves after extraction/wait carrying its cargo',w.order.kind==='move'&&w.x>x&&w.carry===5&&g.money===wallet&&!w.deliveredTrips);
 for(const hold of [false,true]){({w,n}=fixture());tick(49);g.stop(w,hold);const x=w.x;check((hold?'Hold':'Stop')+' waits behind uninterruptible mineral return delay',w.order.phase==='waitReturn'&&w.orders[0]?.kind===(hold?'hold':'stop'));tick(4);check((hold?'Hold':'Stop')+' activates at departure and preserves cargo',!w.order&&w.hold===hold&&w.carry===5&&w.x===x);}
 ({w,n}=fixture(5));tick(45);const {workerStatus}=await import('./resource-presentation.js');const base=g.entities.find(e=>e.type==='core');check('Loaded return-wait worker remains counted on its depleted final field',workerStatus(base,g.entities,g.minerals).count===1);check('Final-field depletion preserves cargo and the wait phase',n.amount===0&&w.carry===5&&w.order.phase==='waitReturn');tick(8);check('A depleted final field still allows its loaded worker to return',w.order.phase==='home'&&w.carry===5);
 ({w,n}=fixture());let deposited=false;for(let i=0;i<200;i++){const before=w.deliveredTrips||0;tick(1);if((w.deliveredTrips||0)>before){deposited=true;break}}check('Deposit begins outbound movement in the same processing loop',deposited&&w.carry===0&&w.order.phase==='out'&&w.vx>0&&g.money===55);
 return out;}''')
 for r in results:print(('PASS' if r['pass'] else 'FAIL'),r['name'],json.dumps(r.get('detail')),flush=True)
 assert all(r['pass'] for r in results),results;assert not errors,errors;print(str(len(results))+' native worker integration checks passed; no browser exceptions.');b.close()
