"""Actual camera/input/billboard checks for reference-backed presentation changes."""
import shutil,json,math
from pathlib import Path
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);page=b.new_page(viewport={'width':1440,'height':900});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game');page.click('#launch');page.evaluate('__game.running=false;__game.aiEnabled=false')
 def check(name,ok,detail=None):print(('PASS' if ok else 'FAIL'),name,json.dumps(detail));assert ok,name
 def state():return page.evaluate('({...__game.camera})')
 check('Default player camera uses fixed 34 game-unit distance',state()['distance']==34*28)
 stops=[(34,56),(30,52),(26,48),(22,44),(18,40)]
 for d,pitch in stops[1:]:
  page.evaluate('__game.running=true');page.keyboard.press('PageUp');page.evaluate('__game.running=false');s=state();check('PageUp selects native distance/pitch stop '+str(d),s['distance']==d*28 and s['pitch']==pitch,s)
 page.evaluate('__game.running=true');page.keyboard.press('PageUp');page.evaluate('__game.running=false');check('Player zoom cannot exceed closest native stop',state()['distance']==18*28)
 for _ in range(8):
  page.evaluate('__game.running=true');page.keyboard.press('PageDown');page.evaluate('__game.running=false')
 check('Player zoom cannot use observer zoom-out distances',state()['distance']==34*28)
 page.set_viewport_size({'width':1280,'height':720});page.wait_for_timeout(100);s=state();check('Resize does not change native camera distance',s['distance']==34*28)
 point1=page.evaluate('__game.view.project(__game.camera.x+80,__game.camera.y-50,0)');page.set_viewport_size({'width':1920,'height':1080});page.wait_for_timeout(100);point2=page.evaluate('__game.view.project(__game.camera.x+80,__game.camera.y-50,0)');check('Same-aspect resize preserves normalized world framing',abs(point1['x']/1280-point2['x']/1920)<1e-6 and abs(point1['y']/720-point2['y']/1080)<1e-6)
 page.set_viewport_size({'width':1440,'height':900});page.wait_for_timeout(100)
 page.keyboard.down('Insert');page.wait_for_timeout(70);check('Insert temporarily rotates camera ninety degrees',abs(state()['yaw']+math.pi/2)<1e-9);before=state();page.evaluate('__game.running=true');page.keyboard.down('ArrowRight');page.wait_for_function(f'__game.camera.y>{before["y"]+10}');page.keyboard.up('ArrowRight');page.evaluate('__game.running=false');after=state();check('Arrow panning follows the temporarily rotated screen axes',after['y']>before['y']+10 and abs(after['x']-before['x'])<1);page.keyboard.up('Insert');page.wait_for_timeout(70);check('Releasing camera rotation restores standard view',state()['yaw']==0)
 page.evaluate('''()=>{const g=__game;g.camera.x=1000;g.camera.y=850;g.view.setCamera(g.camera);const m=g.spawn('marine',0,1000,800);m.hp=3;g.selected=[m];g.updateHUD()}''');page.wait_for_timeout(100)
 r=page.evaluate('''()=>{const g=__game,e=g.selected[0],mesh=g.view.objects.get(e.id);return{rows:g.view.statusBars.get(e.id),color:getComputedStyle(document.querySelector('#healthbar')).backgroundColor,wire:getComputedStyle(document.querySelector('#unitWire'),'::after').backgroundColor,ring:mesh.userData.ring.material.color.getHex(),position:g.view.project(e.x,e.y,18)}}''')
 check('Critical overhead health uses native red independently of team',r['rows'][0]['color']=='#d02200',r);check('HUD health and wireframe use their separate native red values',r['color']=='rgb(208, 34, 0)' and r['wire']=='rgb(255, 0, 0)')
 page.mouse.move(r['position']['x'],r['position']['y']);page.wait_for_timeout(100);check('Actual mesh hover shows dashed preselection alongside selection',page.evaluate('''()=>{const g=__game,m=g.view.objects.get(g.selected[0].id);return g.view.hovered===g.selected[0]&&m.userData.preselection.visible&&m.userData.ring.visible}'''))
 page.mouse.move(1370,820);page.wait_for_timeout(100);check('Moving the cursor into the console clears battlefield hover',page.evaluate('''()=>{const g=__game,m=g.view.objects.get(g.selected[0].id);return g.view.hovered===null&&!m.userData.preselection.visible}'''))
 page.evaluate("__game.selected[0].hp=__game.selected[0].maxhp;__game.updateHUD()");page.wait_for_timeout(50);check('Full life is green regardless of ownership',page.evaluate("__game.view.statusBars.get(__game.selected[0].id)[0].color==='#16e500'"))
 page.evaluate('''()=>{const g=__game;const u=g.spawn('worker',0,1040,850);g.selected=[u,g.entities.find(e=>e.type==='marine'&&!e.team)];g.updateHUD()}''');page.wait_for_timeout(70);check('Active subgroup and other selected units have distinct native ring colors',page.evaluate('''()=>{const g=__game;const a=g.view.objects.get(g.selected[0].id),b=g.view.objects.get(g.selected[1].id);return a.userData.ring.material.color.getHex()===0x00fa19&&b.userData.ring.material.color.getHex()===0x00a85a}'''))
 page.evaluate('''()=>{const g=__game;const c=g.spawn('relay',0,1130,850,false);c.progress=.4;c.hp=c.maxhp*.22;g.selected=[c];g.updateHUD()}''');page.wait_for_timeout(100);r=page.evaluate('__game.view.statusBars.get(__game.selected[0].id)');check('Unfinished buildings show independent life and cyan progress',len(r)==2 and r[0]['kind']=='life' and r[1]['color']=='#00c8c8' and r[0]['ratio']!=r[1]['ratio'],r)
 page.evaluate('''()=>{const g=__game;const c=g.entities.find(e=>e.type==='core'&&!e.team);c.morph='orbital';c.energy=80;g.selected=[c];g.updateHUD()}''');page.wait_for_timeout(100);r=page.evaluate('__game.view.statusBars.get(__game.selected[0].id)');check('Orbital energy has separate native purple bar',r[-1]['kind']=='energy' and r[-1]['color']=='#9628dc' and r[-1]['ratio']==.4)
 page.evaluate('''()=>{const g=__game;g.selected=[];g.camera.x=1000;g.camera.y=850;g.view.setCamera(g.camera);const a=g.spawn('marine',0,900,750),b=g.spawn('marine',1,1100,750);g.stop(a,true);g.stop(b,true);g.update(0);g.testFriendly=a.id;g.testEnemy=b.id}''');page.mouse.move(300,300);page.keyboard.down('[');page.wait_for_timeout(100);r=page.evaluate('({friendly:__game.view.statusBars.has(__game.testFriendly),enemy:__game.view.statusBars.has(__game.testEnemy)})');check('Bracket health key displays friendly bars separately',r['friendly'] and not r['enemy'],r);page.keyboard.up('[')
 page.keyboard.down(']');page.wait_for_timeout(100);r=page.evaluate('({friendly:__game.view.statusBars.has(__game.testFriendly),enemy:__game.view.statusBars.has(__game.testEnemy)})');check('Other bracket health key displays enemy bars separately',not r['friendly'] and r['enemy'],r);page.keyboard.up(']')
 page.evaluate('''()=>{const g=__game;g.selected=[g.spawn('engineering',0,1000,950)];g.updateHUD()}''');page.wait_for_timeout(100);check('Engineering Bay has visible geometry and animated fan',page.evaluate('''()=>{const m=__game.view.objects.get(__game.selected[0].id);return m.userData.buildingAnimation.stages.some(s=>s.children.length)&&!!m.userData.buildingAnimation.fan}'''))
 Path('artifacts').mkdir(exist_ok=True);page.screenshot(path='artifacts/presentation-fidelity.png');check('Presentation has no browser errors',not errors,errors);b.close()
