"""End-to-end remaining control gaps: actual host, dispatch, production and keyboard."""
import json,shutil
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader'])
 page=b.new_page(viewport={'width':1280,'height':800});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game')
 results=page.evaluate('''async()=>{
 const {rallyEndpoints,RALLY_ORDER_LIMIT}=await import('/order-queues.js');
 const g=__game,out=[],check=(name,pass,detail)=>out.push({name,pass:!!pass,detail}),dt=1/22.4,tick=(n=1)=>{for(let i=0;i<n;i++)g.update(dt)};
 const reset=()=>{g.reset();g.start();g.running=false;g.aiEnabled=false;g.entities.splice(0);g.minerals.splice(0);g.money=5000;g.gas=5000;g.selected=[];g.spawn('relay',0,250,1100);g.spawn('core',1,1900,300)};
 const act=(units,id,shift=false)=>{g.selected=units;g.running=true;const r=g.action(id,shift);g.running=false;return r;};
 const cmd=(units,x,y,kind=null,shift=false,picked=null)=>{g.selected=units;g.running=true;const r=g.command(x,y,false,shift,kind,picked);g.running=false;return r;};
 reset();let c=g.spawn('core',0,700,1100);const plan=g.spawn('relay',0,900,1300,false,true),builder=g.spawn('worker',0,850,1050);g.issue(builder,{kind:'build',target:plan});
 let ws=Array.from({length:7},(_,i)=>g.spawn('worker',0,840+i%3*25,1100+Math.floor(i/3)*25));g.invalidateNav();
 check('Load issues only five approach orders and skips the constructing SCV',act([c],'load')&&c.boarding.length===5&&builder.order.kind==='build'&&!ws.some(w=>w.loadedIn));
 check('Repeated Load does not reserve surplus workers',!act([c],'load')&&ws.filter(w=>w.order?.kind==='board').length===5);
 tick(120);check('Five visible approaches really reach and enter the Command Center',c.loaded.length===5&&ws.filter(w=>w.loadedIn===c).length===5,{loaded:c.loaded.length});
 check('Passengers still consume their supply',g.used()===8);g.selected=[c];g.updateHUD();check('Passenger console exposes actual five cargo entries',document.querySelectorAll('#cargo button').length===5&&document.querySelector('#cargo').textContent.includes('5/5'));
 const passenger=c.loaded[0];g.running=true;g.updateHUD();document.querySelector('#cargo button').click();g.running=false;check('Cargo icon unloads only its own passenger',c.loaded.length===4&&!passenger.loadedIn);
 check('Grounded Shift Unload executes immediately rather than waiting for an artificial CC order',act([c],'unload',true)&&!c.order&&c.loaded.length===0);
 const unloaded=ws.filter(w=>!w.loadedIn);check('Unloaded workers have separate positions and continuous interpolation',unloaded.every((w,i)=>unloaded.slice(i+1).every(v=>Math.hypot(w.x-v.x,w.y-v.y)>=w.r+v.r+.49))&&unloaded.every(w=>w.x===w.px&&w.y===w.py));
 reset();c=g.spawn('core',0,700,1100);let w=g.spawn('worker',0,1080,1200);check('Lift makes the CC a flying unit',act([c],'lift')&&c.flying);cmd([c],1050,1100,'move');const flight=c.order;check('Shift Load queues behind a flying Move without commanding workers early',act([c],'load',true)&&c.order===flight&&c.orders[0]?.kind==='loadNearby'&&!w.order);tick(5);check('Queued flying Load remains behind the active movement',c.order===flight&&!w.order);tick(400);check('Queued flying Load activates and collects the nearby SCV',w.loadedIn===c&&c.loaded.length===1,{x:c.x,y:c.y,order:c.order?.kind,worder:w.order?.kind});
 cmd([c],1200,1100,'move');check('Shift Unload queues while a loaded flying CC moves',act([c],'unload',true)&&c.orders[0]?.kind==='unloadAll'&&w.loadedIn===c);tick(3);check('Queued Unload does not eject before the preceding flight finishes',w.loadedIn===c);tick(250);check('Flying CC finishes the queue and unloads the living SCV',c.flying&&!w.loadedIn&&w.hp>0&&!c.order,{x:c.x,order:c.order?.kind});
 reset();c=g.spawn('core',0,700,1100);w=g.spawn('worker',0,880,1100);act([c],'lift');cmd([c],1000,1100,'move');const moving=c.order;check('Unqueued Load preserves an existing flying Move',act([c],'load')&&c.order===moving&&w.order?.kind==='board');tick(350);check('Passenger can board a CC while its original flight continues',w.loadedIn===c);
 reset();c=g.spawn('core',0,700,1100);w=g.spawn('worker',0,820,1100);act([c],'load');tick(80);c.hp=0;tick();check('Destroyed grounded CC ejects its passenger alive',w.hp>0&&!w.loadedIn&&g.entities.includes(w));
 reset();c=g.spawn('core',0,700,1100);w=g.spawn('worker',0,820,1100);act([c],'load');tick(80);act([c],'lift');c.hp=0;tick();check('Destroyed flying CC removes its passenger',w.hp<=0&&!g.entities.includes(w));
 reset();g.spawn('core',0,400,1100);let m=g.spawn('marine',0,700,1100);g.issue(m,{kind:'move',x:1100,y:1100});for(let i=0;i<31;i++)g.issue(m,{kind:'move',x:1100+i,y:1100},true);const head=m.order,tail=m.orders.slice();check('Thirty-two active-plus-queued unit orders are accepted',m.orders.length===31);check('Overflow rejects without altering earlier orders',!cmd([m],1200,1100,'move',true)&&m.order===head&&m.orders.every((o,i)=>o===tail[i])&&document.querySelector('#notice').textContent==='Cannot queue additional orders');
 const free=g.spawn('marine',0,700,1150);check('Mixed selection accepts only available members',cmd([m,free],1250,1150,'move',true)&&m.orders.length===31&&free.order?.kind==='move');
 w=g.spawn('worker',0,600,1100);g.issue(w,{kind:'move',x:900,y:1100});for(let i=0;i<31;i++)g.issue(w,{kind:'move',x:900+i,y:1100},true);g.selected=[w];g.running=true;g.action('relay');g.update(0);const pp=g.placementPreview(630,980),bank=g.money,count=g.entities.length;check('Full worker queue refuses placement before spending or spawning',pp.valid&&!g.place(pp.x,pp.y,true)&&g.money===bank&&g.entities.length===count);g.running=false;
 reset();c=g.spawn('core',0,400,1100);check('First rally plus three queued points are accepted',Array.from({length:4},(_,i)=>cmd([c],700+i*50,1150,'rally',i>0)).every(Boolean)&&c.rallyOrders.length===3);check('Fifth rally point reports the separate four-target cap',RALLY_ORDER_LIMIT===4&&!cmd([c],950,1150,'rally',true)&&c.rallyOrders.length===3&&document.querySelector('#notice').textContent==='Cannot queue additional rally points');
 let leader=g.spawn('marine',0,650,1100);cmd([c],leader.x,leader.y,'rally',false,{entity:leader});cmd([c],1000,1150,'rally',true);leader.x=800;check('Unit-target rally feedback follows the leader instead of the click',rallyEndpoints(c,{visible:g.isVisible})[0].x===800);leader.hp=0;tick();check('Lost unit rally clears its invalid head and promotes the queued ground route',c.rally.kind==='move'&&c.rally.x===1000&&!c.rallyOrders.length);
 const node={x:650,y:1100,r:21,amount:10},near={x:650,y:1140,r:21,amount:100,capacity:100};g.minerals.push(node,near);cmd([c],node.x,node.y,'rally',false,{node});cmd([c],1000,1150,'rally',true);node.amount=0;tick();check('Lost mineral rally preserves Gather at its location and its next waypoint',c.rally.kind==='gatherPoint'&&c.rally.x===650&&c.rallyOrders.length===1);g.running=true;g.selected=[c];g.train('worker');g.running=false;c.queue[0].time=dt;tick(1);const born=g.entities.filter(e=>e.type==='worker').at(-1);check('New SCV inherits Gather-at-point before the queued move',born.order?.kind==='gatherPoint'&&born.orders[0]?.kind==='move');tick(160);check('Nearby minerals are acquired and the queued move begins carrying earned minerals',born.carry===5&&born.order?.kind==='move'&&born.order.x===1000,{order:born.order?.kind,carry:born.carry});
 const barracks=g.spawn('barracks',0,850,1100);barracks.rally={kind:'mine',node:near,x:near.x,y:near.y};barracks.rallyOrders=[{kind:'gatherPoint',x:700,y:1150},{kind:'gas',target:c,x:c.x,y:c.y}];g.train('marine',barracks,true);barracks.queue[0].time=dt;tick();const newborn=g.entities.filter(e=>e.type==='marine').at(-1);check('Every resource rally link becomes a valid ground Move for combat units',newborn.order?.kind==='move'&&newborn.orders.length===2&&newborn.orders.every(o=>o.kind==='move'));
 reset();c=g.spawn('core',0,700,1100);const ref=g.spawn('refinery',0,1000,1100);ref.geyser={amount:2250};w=g.spawn('worker',0,850,1100);g.issue(w,{kind:'gas',target:ref,gatherCommand:'gather'});g.issue(w,{kind:'move',x:800,y:1250},true);let limit=200;while(w.order?.kind==='gas'&&limit--)tick();check('Gas queued Move starts at emergence carrying gas before deposit',w.order?.kind==='move'&&w.carry===4&&g.gas===5000&&!w.insideRefinery);
 g.stop(w);w.carry=0;w.carryGas=false;g.issue(w,{kind:'gas',target:ref});limit=200;while(!w.insideRefinery&&limit--)tick();const progress=w.mineTime;check('Commands cannot manufacture an instant exit from hidden gas extraction',!g.issue(w,{kind:'move',x:700,y:1250})&&w.insideRefinery===ref&&w.mineTime===progress);tick(40);check('Rejected hidden command preserves normal cargo completion',w.carry===4&&!w.insideRefinery);
 reset();g.spawn('core',0,400,1100);w=g.spawn('worker',0,700,1100);let tank=g.spawn('tank',0,840,1100);tank.hp=tank.maxhp-10;w.repairAuto=true;g.stop(w,true);tick(80);check('Held autocast SCV does not chase a distant repair target',w.x===700&&w.hold&&!w.order&&tank.hp===tank.maxhp-10);
 tank.x=735;tank.px=735;tick(40);check('Held SCV repairs a contact target without moving',w.x===700&&tank.hp>tank.maxhp-10);tick(80);check('Hold is restored after autocast finishes',w.hold&&!w.order&&w.x===700&&tank.hp===tank.maxhp);
 reset();g.spawn('core',0,400,1100);w=g.spawn('worker',0,700,1100);tank=g.spawn('tank',0,840,1100);tank.hp=tank.maxhp-10;w.repairAuto=true;tick(160);check('Idle autocast approaches repairs and returns to its original anchor',tank.hp===tank.maxhp&&!w.order&&Math.hypot(w.x-700,w.y-1100)<1.1,{x:w.x,hp:tank.hp,order:w.order?.kind});
 reset();g.spawn('core',0,400,1100);w=g.spawn('worker',0,700,1100);tank=g.spawn('tank',0,820,1100);tank.hp-=10;w.repairAuto=true;g.issue(w,{kind:'move',x:600,y:1100});tick(10);check('Explicit Move overrides repair autocast',w.order?.kind==='move'&&w.x<700&&tank.hp===tank.maxhp-10);
 reset();g.spawn('core',0,400,1100);w=g.spawn('worker',0,700,1100);tank=g.spawn('tank',0,840,1100);tank.hp-=10;w.repairAuto=true;g.money=g.gas=0;tick(40);check('Starved autocast does not acquire an unaffordable repair',!w.order&&w.x===700);g.money=g.gas=100;tick(160);check('New funds allow autocast and its return route',tank.hp===tank.maxhp&&!w.order&&Math.hypot(w.x-700,w.y-1100)<1.1);
 reset();g.spawn('core',0,400,1100);w=g.spawn('worker',0,700,1100);tank=g.spawn('tank',0,735,1100);tank.hp-=10;g.money=0;g.gas=100;check('Unfunded manual Repair is rejected without a movement order',!cmd([w],tank.x,tank.y,'repair',false,{entity:tank})&&!w.order);check('Unfunded Smart repair falls back to Follow',cmd([w],tank.x,tank.y,null,false,{entity:tank})&&w.order?.kind==='follow');
 g.stop(w);g.money=.06;g.gas=100;cmd([w],tank.x,tank.y,'repair',false,{entity:tank});g.issue(w,{kind:'hold'},true);tick(8);const repaired=tank.hp;check('Manual repair ends on resource exhaustion and promotes queued Hold',w.hold&&!w.order&&repaired>tank.maxhp-10&&repaired<tank.maxhp);g.money=100;tick(20);check('Manual repair does not silently resume when funds return',tank.hp===repaired&&w.hold);
 reset();g.spawn('core',0,400,1100);w=g.spawn('worker',0,700,1100);tank=g.spawn('tank',0,735,1100);tank.hp-=10;w.repairAuto=true;g.stop(w,true);tick(2);g.issue(w,{kind:'move',x:650,y:1100},true);tick(120);check('Move queued behind held autocast executes after Repair and its Hold successor',w.x<660&&!w.hold&&!w.order&&tank.hp===tank.maxhp,{x:w.x,hold:w.hold,order:w.order?.kind});
 reset();c=g.spawn('core',0,700,1100);w=g.spawn('worker',0,820,1100);act([c],'load');tick(80);act([c],'lift');cmd([c],1100,1100,'move');const unloadX=c.x,unloadY=c.y;check('Unqueued flying Unload cancels flight and places the first passenger under the Center',act([c],'unload')&&!c.order&&!w.loadedIn&&w.x===unloadX&&w.y===unloadY);
 return out;}''')
 for r in results:print(('PASS' if r['pass'] else 'FAIL'),r['name'],json.dumps(r.get('detail')),flush=True)
 assert all(r['pass'] for r in results),[r for r in results if not r['pass']]
 # Real keyboard Shift Load/Unload while grounded does not interrupt production.
 page.evaluate("()=>{__game.reset();__game.start();__game.aiEnabled=false;__game.running=false;__game.entities.splice(0);__game.minerals.splice(0);const c=__game.spawn('core',0,700,1100);__game.spawn('core',1,1900,300);__game.spawn('worker',0,850,1100);__game.money=5000;__game.selected=[c];__game.running=true;__game.train('worker');}")
 page.keyboard.press('Shift+o');page.evaluate('__game.running=false');assert page.evaluate('__game.entities.find(e=>e.type==="worker"&&!e.building).order?.kind==="board"')
 page.evaluate('for(let i=0;i<100;i++)__game.update(1/22.4)');page.evaluate('__game.running=true');page.keyboard.press('Shift+d');page.evaluate('__game.running=false');assert page.evaluate('__game.selected[0].loaded.length===0&&__game.selected[0].queue.length===1')
 assert not errors,errors
 page.evaluate('__game.camera.x=700;__game.camera.y=1100');page.wait_for_timeout(50);page.screenshot(path='/workspace/sc2-control-lab/artifacts/remaining-details.png')
 print(str(len(results)+2)+' remaining-detail integration checks passed; no browser exceptions.')
 b.close()
