"""Actual Move-to-unit input and native-rate order/pursuit integration."""
import json,shutil
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);page=b.new_page(viewport={'width':1440,'height':900});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8000/?debug');page.wait_for_function('window.__game');page.click('#launch')
 page.evaluate('''()=>{const g=__game;g.running=false;g.aiEnabled=false;for(const e of g.entities.filter(e=>!e.building))g.stop(e,true);const a=g.spawn('marine',0,900,760),t=g.spawn('marine',1,1100,760);g.stop(a,true);g.stop(t,true);t.damage=0;g.selected=[a];g.inputPair={a,t};g.camera.x=1000;g.camera.y=760;g.view.setCamera(g.camera);g.update(0)}''');page.wait_for_timeout(150)
 def check(name,expr):
  okay=page.evaluate(expr);print(('PASS' if okay else 'FAIL'),name,flush=True);assert okay,name
 page.evaluate('__game.running=true');page.keyboard.press('m');point=page.evaluate('__game.view.project(__game.inputPair.t.x,__game.inputPair.t.y,18)');page.mouse.click(point['x'],point['y']);page.evaluate('__game.running=false')
 check('Actual M-click on an enemy issues Follow rather than ground Move or Attack','__game.inputPair.a.order?.kind==="follow"&&__game.inputPair.a.order.target===__game.inputPair.t')
 page.evaluate('''()=>{const g=__game,{a,t}=g.inputPair;t.x=1200;t.px=1200;for(let i=0;i<30;i++)g.update(1/22.4)}''');check('Follow tracks visible target motion without firing','__game.inputPair.a.x>1000&&__game.inputPair.t.hp===__game.inputPair.t.maxhp&&!__game.inputPair.a.visualShotSerial')
 page.evaluate('''()=>{const g=__game,{a,t}=g.inputPair;window.followSeen=a.order.lastSeen.x;t.x=1900;t.y=500;g.update(1/22.4)}''');check('Enemy Follow retains observed coordinates when its target enters fog','__game.inputPair.a.order?.lastSeen.x===followSeen&&followSeen<1500')
 page.evaluate('''()=>{const g=__game,{a,t}=g.inputPair;t.hp=0;g.issue(a,{kind:'hold'},true);g.update(1/22.4)}''');check('Unseen target death does not instantly consume a Follow order','__game.inputPair.a.order?.kind==="follow"&&__game.inputPair.a.orders[0]?.kind==="hold"')
 page.evaluate('for(let i=0;i<120;i++)__game.update(1/22.4)');check('Reaching the last observed Follow point promotes its queued Hold','__game.inputPair.a.hold&&!__game.inputPair.a.order')
 results=page.evaluate('''()=>{
 const g=__game,dt=1/22.4,out=[],check=(name,pass,detail=null)=>out.push({name,pass:!!pass,detail});
 const reset=()=>{g.reset();g.start();g.running=false;g.aiEnabled=false;for(const e of g.entities.filter(e=>!e.building))g.stop(e,true)};
 reset();const a=g.spawn('marine',0,700,500),t=g.spawn('marine',1,890,500);g.stop(t,true);t.damage=0;g.update(0);g.issue(a,{kind:'attack',target:t});g.issue(a,{kind:'move',x:600,y:650},true);const accepted=a.order.acceptedLoop,x=a.x;t.x=1750;t.y=400;g.update(dt);check('An explicit attack captures its visible target before the first loop',a.order?.kind==='attackMove'&&a.order.x===890&&a.order.y===500);check('Fog fallback continues moving in the same loop without a stopped frame',a.x>x);check('Fog fallback preserves queue and acknowledgement metadata',a.order.acceptedLoop===accepted&&a.orders.length===1&&a.orders[0].x===600);check('A fog fallback has no live hidden-target pointer in its waypoint',!a.order.target);t.x=850;t.y=500;g.update(dt);check('A visible original attack target regains explicit preference',a.order?.kind==='attack'&&a.order.target===t);
 reset();const hiddenAttack=g.spawn('marine',0,700,500),hiddenTarget=g.spawn('marine',1,890,500);g.stop(hiddenTarget,true);hiddenTarget.damage=0;g.update(0);g.issue(hiddenAttack,{kind:'attack',target:hiddenTarget});g.issue(hiddenAttack,{kind:'hold'},true);const hiddenStart=hiddenAttack.x;hiddenTarget.x=1750;hiddenTarget.y=400;hiddenTarget.hp=0;g.update(dt);check('Unseen explicit-target death still pursues the accepted observed position',hiddenAttack.order?.kind==='attackMove'&&hiddenAttack.order.x===890&&hiddenAttack.x>hiddenStart);check('Unseen explicit-target death preserves the queued successor',hiddenAttack.orders[0]?.kind==='hold'&&!hiddenAttack.order.target);
 reset();const p=g.spawn('marine',0,700,850);g.selected=[p];g.issue(p,{kind:'move',x:850,y:850});g.running=true;g.command(1050,850,false,true,'patrol');g.running=false;check('Queued Patrol defers its return origin until activation',p.orders[0].origin===null);for(let i=0;i<100&&p.order?.kind!=='patrol';i++)g.update(dt);check('Queued Patrol starts from the reached waypoint rather than the old issuing point',p.order?.kind==='patrol'&&p.order.origin.x>840&&Math.abs(p.order.origin.y-850)<4,p.order);for(let i=0;i<220;i++)g.update(dt);check('Patrol returns between its activated origin and endpoint',p.order?.kind==='patrol'&&p.x>830);
 reset();const target=g.spawn('tank',1,1040,900);target.damage=0;target.hp=target.maxhp=2000;g.stop(target,true);const squad=[];for(let i=0;i<24;i++)squad.push(g.spawn('worker',0,900-i%6*18,860+Math.floor(i/6)*20));g.selected=squad;g.running=true;g.command(1300,700,true,false,'attack');g.running=false;const squadGoals=new Map(squad.map(e=>[e.id,{x:e.order.x,y:e.order.y}]));for(let i=0;i<200;i++)g.update(dt);check('A reserved Attack Move squad pursues and hits its encountered enemy',target.hp<2000,{hp:target.hp,shots:squad.reduce((n,e)=>n+(e.visualShotSerial||0),0)});check('Temporary combat keeps the squad march destination',squad.filter(e=>e.order).every(e=>e.order.kind==='attackMove'&&e.order.x===squadGoals.get(e.id).x&&e.order.y===squadGoals.get(e.id).y));
 for(const type of ['worker','marine','marauder','reaper','hellion','tank']){reset();const u=g.spawn(type,0,950,850),enemy=g.spawn('marine',1,1030,850);enemy.damage=0;enemy.hp=enemy.maxhp=1000;g.stop(enemy,true);g.issue(u,{kind:'attack',target:enemy});g.issue(u,{kind:'move',x:1200,y:850},true);for(let i=0;i<240;i++)g.update(dt);check(type+' closes or fires on its explicit target without dropping its successor',enemy.hp<1000&&u.orders[0]?.kind==='move',{hp:enemy.hp,shots:u.visualShotSerial||0,x:u.x});}
 return out;
 }''')
 for r in results:print(('PASS' if r['pass'] else 'FAIL'),r['name'],json.dumps(r['detail']),flush=True)
 assert all(r['pass'] for r in results),[r for r in results if not r['pass']];assert not errors,errors;print(str(5+len(results))+' unit intent integration checks passed; no browser exceptions.');b.close()
